//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 05:58:30 PM CEST 
//


package it.bancomatpay.sdk.manager.network.dto;

import java.io.Serializable;
import java.util.List;


public class DtoBankData implements Serializable {


    protected String bankUUID;
    protected boolean multiIban;
    protected List<DtoInstrument> instruments;
    protected String bankName;
    protected String urlAppIos;
    protected String urlAppAndroid;
    protected String urlAppWP;
    protected String urlImg;
    protected ActionType action;

    /**
     * Gets the value of the bankUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankUUID() {
        return bankUUID;
    }

    /**
     * Sets the value of the bankUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankUUID(String value) {
        this.bankUUID = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the urlAppIos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlAppIos() {
        return urlAppIos;
    }

    /**
     * Sets the value of the urlAppIos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlAppIos(String value) {
        this.urlAppIos = value;
    }

    /**
     * Gets the value of the urlAppAndroid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlAppAndroid() {
        return urlAppAndroid;
    }

    /**
     * Sets the value of the urlAppAndroid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlAppAndroid(String value) {
        this.urlAppAndroid = value;
    }

    /**
     * Gets the value of the urlAppWP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlAppWP() {
        return urlAppWP;
    }

    /**
     * Sets the value of the urlAppWP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlAppWP(String value) {
        this.urlAppWP = value;
    }

    /**
     * Gets the value of the urlImg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlImg() {
        return urlImg;
    }

    /**
     * Sets the value of the urlImg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlImg(String value) {
        this.urlImg = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    public boolean isMultiIban() {
        return multiIban;
    }

    public void setMultiIban(boolean multiIban) {
        this.multiIban = multiIban;
    }

    public List<DtoInstrument> getInstruments() {
        return instruments;
    }

    public void setInstruments(List<DtoInstrument> instruments) {
        this.instruments = instruments;
    }

}
