//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.07.04 at 11:37:35 AM CEST
//

package it.bancomat.pay.consumer.network.dto.request;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;


public class DtoPinCrypted implements Serializable {

    @SerializedName("t")
    protected String salt;
    @SerializedName("u")
    protected long iteratorCounter;
    @SerializedName("v")
    protected String payload;
    @SerializedName("z")
    protected String cryptInfo;

    /**
     * Gets the value of the cryptInfo property.
     *
     * @return possible object is {@link String }
     */
    public String getCryptInfo() {
        return cryptInfo;
    }

    /**
     * Gets the value of the iteratorCounter property.
     */
    public long getIteratorCounter() {
        return iteratorCounter;
    }

    /**
     * Gets the value of the payload property.
     *
     * @return possible object is {@link String }
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Gets the value of the salt property.
     *
     * @return possible object is {@link String }
     */
    public String getSalt() {
        return salt;
    }

    /**
     * Sets the value of the cryptInfo property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCryptInfo(String value) {
        this.cryptInfo = value;
    }

    /**
     * Sets the value of the iteratorCounter property.
     */
    public void setIteratorCounter(long value) {
        this.iteratorCounter = value;
    }

    /**
     * Sets the value of the payload property.
     *
     * @param value allowed object is {@link String }
     */
    public void setPayload(String value) {
        this.payload = value;
    }

    /**
     * Sets the value of the salt property.
     *
     * @param value allowed object is {@link String }
     */
    public void setSalt(String value) {
        this.salt = value;
    }

}
