//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.08 at 11:52:20 AM CEST 
//


package it.bancomatpay.sdk.manager.network.dto.response;

import java.io.Serializable;

import it.bancomatpay.sdk.manager.network.dto.PaymentStateType;


public class DtoConfirmPaymentRequestResponse
    implements Serializable
{

    protected PaymentStateType paymentState;
    protected String lastAttempts;

    /**
     * Gets the value of the paymentState property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentStateType }
     *     
     */
    public PaymentStateType getPaymentState() {
        return paymentState;
    }

    /**
     * Sets the value of the paymentState property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentStateType }
     *     
     */
    public void setPaymentState(PaymentStateType value) {
        this.paymentState = value;
    }

    /**
     * Gets the value of the lastAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastAttempts() {
        return lastAttempts;
    }

    /**
     * Sets the value of the lastAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastAttempts(String value) {
        this.lastAttempts = value;
    }

}
