package it.bancomatpay.sdk.manager.model;

public enum ECashbackActivationResult {
	SUBSCRIBED_SUCCESS, SUBSCRIBED_FAILURE, SUBSCRIBED_UNDEFINED, BPAY_UNSUBSCRIBED_SUCCESS, BPAY_UNSUBSCRIBED_FAILURE, CASHBACK_DISABLING_SUCCESS, CASHBACK_DISABLING_FAILED, CASHBACK_DISABLING_FAILED_DUE_TO_OTHER_INSTRUMENTS
}
